export const items = [
    {
        name: "t-shirt",
        price: 100,
        style: "t-shirt",
        size: "medium",
        color: "blue",
    },
    {
        name: "pants",
        price: 200,
        style: "pants",
        size: "medium",
        color: "blue",
    },
    {
        name: "shoes",
        price: 300,
        style: "shoes",
        size: "medium",
        color: "blue",
    },
    {
        name: "hat",
        price: 400,
        style: "hat",
        size: "medium",
        color: "blue",
    },
    {
        name: "gloves",
        price: 500,
        style: "gloves",
        size: "medium",
        color: "blue",
    },
    {
        name: "scarf",
        price: 600,
        style: "scarf",
        size: "medium",
        color: "blue",
    },
    {
        name: "belt",
        price: 700,
        style: "belt",
        size: "medium",
        color: "blue",
    },
    {
        name: "socks",
        price: 800,
        style: "socks",
        size: "medium",
        color: "blue",
    },
    {
        name: "watch",
        price: 900,
        style: "watch",
        size: "medium",
        color: "blue",
    },
    {
        name: "bracelet",
        price: 1000,
        style: "bracelet",
        size: "medium",
        color: "blue",
    },
    {
        name: "necklace",
        price: 1100,
        style: "necklace",
        size: "medium",
        color: "blue",
    },
    {
        name: "earrings",
        price: 1200,
        style: "earrings",
        size: "medium",
        color: "blue",
    },
    {
        name: "ring",
        price: 1300,
        style: "ring",
        size: "medium",
        color: "blue",
    },
    {
        name: "sunglasses",
        price: 1400,
        style: "sunglasses",
        size: "medium",
        color: "blue",
    },
    {
        name: "backpack",
        price: 1500,
        style: "backpack",
        size: "medium",
        color: "blue",
    },
    {
        name: "purse",
        price: 1600,
        style: "purse",
        size: "medium",
        color: "blue",
    },
    {
        name: "wallet",
        price: 1700,
        style: "wallet",
        size: "medium",
    }
]

